services:
  postgres:
    image: postgres:16
    container_name: centro_pokemon_db
    restart: always
    env_file:
      - .env
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./migrations/02_roles.sql:/docker-entrypoint-initdb.d/02_roles.sql

volumes:
  postgres_data: